### ISSUE TITLE
XpsMiner.cpp:3329:28: error: expected unqualified-id before '->' token

### ISSUE THREAD

**Issue by kahose** [xrpinals/XpsMiner#1]
XpsMiner.cpp:3329:28: error: expected unqualified-id before '->' token
 3329 |                 break; work->data
      |                            ^~
make[2]: *** [Makefile:1220: XpsMiner-XpsMiner.o] Error 1
mv -f .deps/XpsMiner-hashlog.Tpo .deps/XpsMiner-hashlog.Po
mv -f .deps/XpsMiner-nvml.Tpo .deps/XpsMiner-nvml.Po
make[2]: Leaving directory '/root/XpsMiner'
make[1]: *** [Makefile:1394: all-recursive] Error 1
make[1]: Leaving directory '/root/XpsMiner'
make: *** [Makefile:526: all] Error 2

**Comment by xrpinals** [comment]
Really appreciate with you for this issue.
