### ISSUE TITLE
util.cpp:1883:1: error: jump to label 'out'

### ISSUE THREAD

**Issue by kahose** [xrpinals/XpsMiner#2]
util.cpp: In function 'bool stratum_notify(stratum_ctx*, json_t*)':
util.cpp:1883:1: error: jump to label 'out'
 1883 | out:
      | ^~~
util.cpp:1819:30: note:   from here
 1819 |                         goto out;
      |                              ^~~
util.cpp:1850:14: note:   crosses initialization of 'int p'
 1850 |         int  p = 0;
      |              ^
util.cpp:1849:14: note:   crosses initialization of 'bool ret'
 1849 |         bool ret = false;
      |              ^~~
make[2]: *** [Makefile:1248: XpsMiner-util.o] Error 1
make[2]: *** Waiting for unfinished jobs....
mv -f .deps/XpsMiner-sysinfos.Tpo .deps/XpsMiner-sysinfos.Po
XpsMiner.cpp:198:17: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
  198 | char *rpc_url = "stratum+tcp://127.0.0.1:42123";
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
XpsMiner.cpp:200:27: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
  200 | char *default_user_name = "xpsminer001";
      |                           ^~~~~~~~~~~~~
mv -f .deps/XpsMiner-stats.Tpo .deps/XpsMiner-stats.Po
XpsMiner.cpp: In function 'int share_result(int, int, double, const char*)':
XpsMiner.cpp:693:51: warning: '__builtin___sprintf_chk' writing a terminating nul past the end of the destination [-Wformat-overflow=]
  693 |                 sprintf(solved, " solved %u blocks", p->solved_count);
      |                                                   ^
In file included from /usr/include/stdio.h:894,
                 from XpsMiner.cpp:40:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:38:34: note: '__builtin___sprintf_chk' output between 17 and 26 bytes into a destination of size 16
   38 |   return __builtin___sprintf_chk (__s, __USE_FORTIFY_LEVEL - 1,
      |          ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   39 |                                   __glibc_objsize (__s), __fmt,
      |                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   40 |                                   __va_arg_pack ());
      |                                   ~~~~~~~~~~~~~~~~~
mv -f .deps/XpsMiner-XpsMiner.Tpo .deps/XpsMiner-XpsMiner.Po
make[2]: Leaving directory '/root/XpsMiner'
make[1]: *** [Makefile:1394: all-recursive] Error 1
make[1]: Leaving directory '/root/XpsMiner'
make: *** [Makefile:526: all] Error 2

**Comment by ETpaladin** [comment]
me too

**Comment by ETpaladin** [comment]
Makefile:1212: recipe for target 'XpsMiner-util.o' failed
make[2]: *** [XpsMiner-util.o] Error 1
make[2]: *** Waiting for unfinished jobs....
mv -f .deps/XpsMiner-stats.Tpo .deps/XpsMiner-stats.Po
mv -f .deps/XpsMiner-nvml.Tpo .deps/XpsMiner-nvml.Po
mv -f .deps/XpsMiner-cuda.Tpo .deps/XpsMiner-cuda.Po
make[2]: Leaving directory '/home/ubuntu/XpsMiner'
Makefile:1358: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/ubuntu/XpsMiner'
Makefile:496: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by xrpinals** [comment]
Maybe it is the problem of  `curl-for-windows` , 
please try 

```
cd XpsMiner/compat
git clone https://github.com/xrpinals/curl-for-windows
cd curl-for-windows
git submodule update --init --recursive
```

or use the zip file curl-for-windows.zip to instead of.
